version: '3'

services:
  sucotron:
    build: .
    image: ${SUCOTRON_IMAGE-constructionsincongrues/sucotron}:${SUCOTRON_VERSION-develop}
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - .:/usr/local/src/sucotron
