version: '3'

services:
  sucotron:
    build: .
    env_file: .env
    image: constructionsincongrues/sucotron:${SUCOTRON_VERSION-latest}
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - .:/usr/local/src/sucotron